# Cloudflare Pages configuration
name = "organize-directory"

# Compatibility settings
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

# Pages specific config
[site]
bucket = "./"

# Build settings
[build]
command = ""
[build.upload]
format = "directory" 