name = "organize-directory"
main = "./"

# Configure Pages
[site]
bucket = "./"

# Configure build settings
[build]
command = ""
# Set the directory to be deployed
output_dir = "./"

# Required for Cloudflare Pages
[build.upload]
format = "directory" 