/**
 * migrate.js
 *
 * One-time migration from hand-authored HTML → structured JSON.
 *
 * Reads:  cities/*.html, states/*.html, topics/*.html
 * Writes: data/locations/*.json, data/states/*.json, data/topics/*.json
 *
 * Run with: node scripts/migrate.js
 * Add --dry-run to preview without writing files.
 */

import * as cheerio from 'cheerio';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const DRY_RUN = process.argv.includes('--dry-run');

// ─── Helpers ────────────────────────────────────────────────────────────────

function loadHtml(content) {
  return cheerio.load(content, { decodeEntities: false });
}

// Slug from a URL like "/new-york" or "/cities/brooklyn" → "new-york" / "brooklyn"
function slugFromHref(href) {
  if (!href) return null;
  return href.replace(/^\/+/, '').replace(/\.html$/, '').split('/').pop() || null;
}

// Best-effort title extraction — falls back to <title> and og:title when <h1> is missing
function extractTitle($) {
  const h1 = $('h1').first().text().trim();
  if (h1) return h1;

  for (const raw of [
    $('title').first().text(),
    $('meta[property="og:title"]').attr('content') || '',
  ]) {
    const cleaned = raw.trim()
      .replace(/^Mutual Aid in\s+/i, '')
      .replace(/\s+Mutual Aid Networks.*/i, '')
      .replace(/\s+-\s+.*/, '')
      .replace(/\s+\|.*/, '')
      .trim();
    if (cleaned) return cleaned;
  }

  return null;
}

// All CSS class names used for initiative-like blocks across hand-authored pages
const INITIATIVE_SELECTOR =
  '.initiative, .initative, .organization, .organization-item, .resource-item, .resource-content';

// Extract initiatives from a section element
function extractInitiatives($, sectionEl) {
  const initiatives = [];
  $(sectionEl).find(INITIATIVE_SELECTOR).each((_, el) => {
    const $el = $(el);
    const $a = $el.find('a').first();
    const name = $a.text().trim();
    const url = $a.attr('href')?.trim() || '';
    const description = $el.find('p').first().text().trim();
    // Only include external links (skip internal city links, etc.)
    if (name && url && (url.startsWith('http') || url.startsWith('//'))) {
      initiatives.push({ name, url, ...(description ? { description } : {}) });
    }
  });
  return initiatives;
}

// Returns true if a section is purely a children-links list (no initiative divs)
function isChildrenSection($, sectionEl) {
  const hasInitiatives = $(sectionEl).find(INITIATIVE_SELECTOR).length > 0;
  const hasCityLinks = $(sectionEl).find('.city-link, .location-link').length > 0;
  return hasCityLinks && !hasInitiatives;
}

// ─── Location (cities + regions) ────────────────────────────────────────────

async function migrateLocation(filePath) {
  const slug = path.basename(filePath, '.html');
  const content = await fs.readFile(filePath, 'utf-8');
  const $ = loadHtml(content);

  // Title — fall back through <title> tag and og:title if <h1> is absent
  const title = extractTitle($);
  if (!title) return { slug, error: 'no title found (no <h1>, <title>, or og:title)' };

  // Breadcrumb → infer state + parent
  let state = null;
  let parent = null;

  const breadcrumbLinks = $('.breadcrumb a').toArray();

  if (breadcrumbLinks.length > 0) {
    // Skip a leading "States" / "Locations" link that just points back to the index
    let startIdx = 0;
    const firstHref = $(breadcrumbLinks[0]).attr('href') || '';
    if (firstHref.includes('location') || firstHref.includes('states')) {
      startIdx = 1;
    }

    const meaningful = breadcrumbLinks.slice(startIdx);

    if (meaningful.length > 0) {
      // First meaningful link = the state page
      state = slugFromHref($(meaningful[0]).attr('href'));

      // Last meaningful link = direct parent
      // (if there's only one, parent === state, e.g. a city directly under a state)
      parent = slugFromHref($(meaningful[meaningful.length - 1]).attr('href'));
    }
  }

  // Sections — try all <section> elements; skip children-link-only sections
  const sections = [];
  $('section').each((_, sectionEl) => {
    if (isChildrenSection($, sectionEl)) return; // will be auto-generated by build

    const id = $(sectionEl).attr('id') || `section-${sections.length}`;
    const sectionTitle = $(sectionEl).find('h2').first().text().trim();
    const initiatives = extractInitiatives($, sectionEl);

    if (initiatives.length > 0) {
      sections.push({ id, title: sectionTitle, initiatives });
    }
  });

  // Fallback: flat initiatives not inside any <section> (e.g. in .initiatives-list or bare in main)
  if (sections.length === 0) {
    const flatInitiatives = extractInitiatives($, 'main, body');
    if (flatInitiatives.length > 0) {
      sections.push({ id: 'main', title: '', initiatives: flatInitiatives });
    }
  }

  const result = { slug, title };
  if (state) result.state = state;
  if (parent) result.parent = parent;
  result.sections = sections;

  return result;
}

// ─── States ─────────────────────────────────────────────────────────────────

async function migrateState(filePath) {
  const slug = path.basename(filePath, '.html');
  const content = await fs.readFile(filePath, 'utf-8');
  const $ = loadHtml(content);

  const title = extractTitle($);
  if (!title) return { slug, error: 'no title found' };

  const sections = [];

  // State pages use plain <section> without id/class — find sections that
  // have initiatives (skip the Cities link-list section)
  $('section').each((_, sectionEl) => {
    if (isChildrenSection($, sectionEl)) return;

    const sectionTitle = $(sectionEl).find('h2').first().text().trim();
    const initiatives = extractInitiatives($, sectionEl);

    if (initiatives.length > 0) {
      const id = sectionTitle.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') || `section-${sections.length}`;
      sections.push({ id, title: sectionTitle, initiatives });
    }
  });

  return { slug, title, sections };
}

// ─── Topics ─────────────────────────────────────────────────────────────────

async function migrateTopic(filePath) {
  const slug = path.basename(filePath, '.html');
  const content = await fs.readFile(filePath, 'utf-8');
  const $ = loadHtml(content);

  const title = extractTitle($);
  if (!title) return { slug, error: 'no title found' };

  const subtitle = $('.subtitle').first().text().trim() || null;

  // Topics use .initiatives-section or flat .initiative divs
  const sections = [];
  const allSections = $('section.initiatives-section, section.city-section, section[id]').toArray();

  if (allSections.length > 0) {
    allSections.forEach((sectionEl, i) => {
      const sectionTitle = $(sectionEl).find('h2').first().text().trim();
      const initiatives = extractInitiatives($, sectionEl);
      if (initiatives.length > 0) {
        const id = $(sectionEl).attr('id') || sectionTitle.toLowerCase().replace(/[^a-z0-9]+/g, '-') || `section-${i}`;
        sections.push({ id, title: sectionTitle, initiatives });
      }
    });
  } else {
    // Flat list
    const initiatives = extractInitiatives($, 'body');
    if (initiatives.length > 0) {
      sections.push({ id: 'main', title: '', initiatives });
    }
  }

  const result = { slug, title };
  if (subtitle) result.subtitle = subtitle;
  result.sections = sections;

  return result;
}

// ─── Main ────────────────────────────────────────────────────────────────────

async function run() {
  console.log(DRY_RUN ? '🔍 DRY RUN — no files will be written\n' : '🚀 Migrating HTML → JSON\n');

  const warnings = [];
  let locationCount = 0, stateCount = 0, topicCount = 0;

  // ── Locations (cities/) ──────────────────────────────────────────────────
  console.log('── Locations (cities/) ──');
  const cityFiles = (await fs.readdir(path.join(ROOT, 'cities')))
    .filter(f => f.endsWith('.html'))
    .sort();

  for (const file of cityFiles) {
    const data = await migrateLocation(path.join(ROOT, 'cities', file));

    if (data.error) {
      warnings.push(`locations/${data.slug}: ${data.error}`);
      continue;
    }

    if (!data.parent) {
      warnings.push(`locations/${data.slug}: no parent found — needs manual review`);
    }

    if (!data.state) {
      warnings.push(`locations/${data.slug}: no state found — needs manual review`);
    }

    const totalInitiatives = data.sections.reduce((n, s) => n + s.initiatives.length, 0);
    console.log(`  ✓ ${data.slug.padEnd(35)} parent=${String(data.parent || '?').padEnd(20)} initiatives=${totalInitiatives}`);

    if (!DRY_RUN) {
      await fs.writeFile(
        path.join(ROOT, 'data/locations', `${data.slug}.json`),
        JSON.stringify(data, null, 2),
        'utf-8'
      );
    }
    locationCount++;
  }

  // ── States ───────────────────────────────────────────────────────────────
  console.log('\n── States ──');
  const stateFiles = (await fs.readdir(path.join(ROOT, 'states')))
    .filter(f => f.endsWith('.html'))
    .sort();

  for (const file of stateFiles) {
    const data = await migrateState(path.join(ROOT, 'states', file));

    if (data.error) {
      warnings.push(`states/${data.slug}: ${data.error}`);
      continue;
    }

    const totalInitiatives = data.sections.reduce((n, s) => n + s.initiatives.length, 0);
    console.log(`  ✓ ${data.slug.padEnd(35)} initiatives=${totalInitiatives}`);

    if (!DRY_RUN) {
      await fs.writeFile(
        path.join(ROOT, 'data/states', `${data.slug}.json`),
        JSON.stringify(data, null, 2),
        'utf-8'
      );
    }
    stateCount++;
  }

  // ── Topics ───────────────────────────────────────────────────────────────
  console.log('\n── Topics ──');
  const topicFiles = (await fs.readdir(path.join(ROOT, 'topics')))
    .filter(f => f.endsWith('.html'))
    .sort();

  for (const file of topicFiles) {
    const data = await migrateTopic(path.join(ROOT, 'topics', file));

    if (data.error) {
      warnings.push(`topics/${data.slug}: ${data.error}`);
      continue;
    }

    const totalInitiatives = data.sections.reduce((n, s) => n + s.initiatives.length, 0);
    console.log(`  ✓ ${data.slug.padEnd(35)} initiatives=${totalInitiatives}`);

    if (!DRY_RUN) {
      await fs.writeFile(
        path.join(ROOT, 'data/topics', `${data.slug}.json`),
        JSON.stringify(data, null, 2),
        'utf-8'
      );
    }
    topicCount++;
  }

  // ── Summary ──────────────────────────────────────────────────────────────
  console.log(`
── Summary ──
  Locations : ${locationCount}
  States    : ${stateCount}
  Topics    : ${topicCount}
  Total     : ${locationCount + stateCount + topicCount}
`);

  if (warnings.length > 0) {
    console.log(`⚠️  ${warnings.length} items need attention:\n`);
    warnings.forEach(w => console.log(`  • ${w}`));
    console.log('');
  } else {
    console.log('✅ No warnings — all pages migrated cleanly.');
  }

  if (DRY_RUN) {
    console.log('(Dry run complete — rerun without --dry-run to write files)');
  }
}

run().catch(err => {
  console.error('Migration failed:', err);
  process.exit(1);
});
